export default {
  LOAD_APPLICANTS: 'LOAD_APPLICANTS',
  CLEAR_ALL_TAGS: 'CLEAR_ALL_TAGS',
  DELETE_TAG: 'DELETE_TAG',
  FILTER_APPLICANT_STATUS: 'FILTER_APPLICANT_STATUS',
  SEARCH: 'SEARCH',
  UPDATE_STATUS: 'UPDATE_STATUS'
}
